name: Build and Test FAHPWebApp3

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore FAHP.sln

      - name: Build (Release)
        run: dotnet build FAHP.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test FAHPWebApp3.Tests/FAHPWebApp3.Tests.csproj --configuration Release --no-build

      - name: Publish FAHPWebApp3.Browser
        run: dotnet publish FAHPWebApp3/FAHPWebApp3.Browser/FAHPWebApp3.Browser.csproj --configuration Release --output ./publish

      - name: Upload artifact (published app)
        uses: actions/upload-artifact@v4
        with:
          name: FAHPWebApp3_publish
          path: ./publish/**   